apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jdbc-postgres-sink-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster3
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    topics: "example"
    connection.url: "jdbc:postgresql://postgres-service.kafka.svc.cluster.local:5432/postgres"
    connection.user: "postgres"
    connection.password: "Dankook1!"
    auto.create: "true"        # 대상 테이블 자동 생성
    auto.evolve: "true"        # 스키마 변경 시 컬럼 자동 추가
    insert.mode: "upsert"      # PK 기준 insert/update
    pk.mode: "record_value"    # 레코드 값에서 PK 추출
    pk.fields: "id"            # PK 컬럼명
 
