version: "3.7"
services:
  namenode:
    image: test/hadoop
    ports:
        - "9870:9870"
        - "8088:8088"
    command: >
      bash -c "hdfs namenode & yarn resourcemanager "
    hostname: hdfs-namenode

  datanode1:
    image: test/hadoop
    hostname: datanode1
    depends_on:
        - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager "
    ports:
# The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
      - "9864"
    links:
        - namenode:hdfs-namenode

  datanode2:
    image: test/hadoop
    hostname: datanode2
    depends_on:
        - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager "
    ports:
# The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
      - "9864"
    links:
        - namenode:hdfs-namenode

  datanode3:
    image: test/hadoop
    hostname: datanode3
    depends_on:
        - namenode
    command: >
     bash -c "hdfs datanode & yarn nodemanager "
    ports:
# The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
      - "9864"
    links:
        - namenode:hdfs-namenode


  secondarynamenode:
    image: test/hadoop
    command: hdfs secondarynamenode
    ports:
        - "9868:9868"
    links:
        - namenode:hdfs-namenode
